# Generated by Django 5.0.4 on 2024-05-18 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pentest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.IntegerField(choices=[(1, 'Web-application'), (2, 'Network'), (3, 'Cloud')])),
                ('typeS', models.IntegerField(choices=[(1, 'Web-based'), (2, 'Mobile'), (3, 'Network')])),
                ('toolsC', models.IntegerField(choices=[(1, 'Web-application'), (2, 'Network'), (3, 'Code-analysis'), (4, 'Password-Cracking')])),
                ('platform', models.IntegerField(choices=[(1, 'Windows'), (2, 'Linux'), (3, 'MacOS'), (4, 'Cloud')])),
            ],
        ),
    ]
